version: '3.7'

services:
 
  api:
    image: eassbhhtgu/elgatoapi:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+
      EndPoints:NetworkDiscoveryApi: http://discovery
    ports:
    - 46273:80/tcp

  discovery:
    image: eassbhhtgu/networkdiscoveryapi:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+
      Router:PathToPrivateKey: /run/secrets/id_rsa
      Router:PathToPublicKey: /run/secrets/id_rsa.pub
    secrets:
    - source: id_rsa
    - source: id_rsa.pub

secrets:
  id_rsa:
    file: ${USERPROFILE}\.ssh\id_rsa
  id_rsa.pub:
    file: ${USERPROFILE}\.ssh\id_rsa.pub
