version: '3.7'

services:
 
  api:
    image: eassbhhtgu/elgatoapi:latest
    entrypoint: bash -c "/usr/sbin/update-ca-certificates && dotnet ElgatoApi.WebApplication.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: /run/secrets/localhost.key
      ASPNETCORE_Kestrel__Certificates__Default__Path: /run/secrets/localhost.crt
      ASPNETCORE_HTTPS_PORT: "443"
      ASPNETCORE_URLS: https://+
      EndPoints:NetworkDiscoveryApi: https://networkdiscovery
      Identity:Authority: https://identityserver
      Identity:ClientId: elgatoapi
      Identity:ClientSecret: 8556e52c6ab90d042bb83b3f0c8894498beeb65cf908f519a2152aceb131d3ee
      Identity:Scope: networkdiscovery
    ports:
    - 46274:443/tcp
    secrets:
    - source: localhost.crt
    - source: localhost.key
    - source: ca.crt
      target: /usr/local/share/ca-certificates/ca.crt

secrets:
  id_rsa:
    file: ${USERPROFILE}\.ssh\id_rsa
  ca.crt:
    file: ${USERPROFILE}\.aspnet\https\ca.crt
  localhost.crt:
    file: ${USERPROFILE}\.aspnet\https\elgatoapi.crt
  localhost.key:
    file: ${USERPROFILE}\.aspnet\https\elgatoapi.key
