version: '3.7'

services:
 
  api:
    image: eassbhhtgu/elgatoapi:latest
    entrypoint: bash -c "/usr/sbin/update-ca-certificates && dotnet ElgatoApi.WebApplication.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTPS_PORT: "443"
      ASPNETCORE_URLS: https://+
      EndPoints:NetworkDiscoveryApi: https://discovery
      Kestrel:Certificates:Default:KeyPath: /run/secrets/localhost.key
      Kestrel:Certificates:Default:Path: /run/secrets/localhost.crt
    ports:
    - 46274:443/tcp
    secrets:
    - source: localhost.crt
    - source: localhost.key
    volumes:
    - ~/.aspnet/https/ca.crt:/usr/local/share/ca-certificates/ca.crt:ro

  discovery:
    image: eassbhhtgu/networkdiscoveryapi:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTPS_PORT: "443"
      ASPNETCORE_URLS: https://+
      Kestrel:Certificates:Default:KeyPath: /run/secrets/discovery.key
      Kestrel:Certificates:Default:Path: /run/secrets/discovery.crt
      Router:PathToPrivateKey: /run/secrets/id_rsa
    secrets:
    - source: discovery.crt
    - source: discovery.key
    - source: id_rsa

secrets:
  id_rsa:
    file: ${USERPROFILE}\.ssh\id_rsa
  discovery.crt:
    external: true
    name: discovery.crt
  discovery.key:
    external: true
    name: discovery.key
  localhost.crt:
    external: true
    name: localhost.crt
  localhost.key:
    external: true
    name: localhost.key
